#!/bin/bash

cdg () {
    if [[ -z "$1" ]]; then
        echo "changing to $1"
        cd $1
    fi

    if [ -f .venv/bin/activate ]; then
	    . .venv/bin/activate
    fi
}

_cdg() {
    COMPREPLY=()
    local cur projects
    projects=$(find -maxdepth 3 -name .git -printf "%h\n" 2>/dev/null)
    _get_comp_words_by_ref cur
    COMPREPLY=( $(compgen -W "${projects}" -- ${cur}) )
}

complete -F _cdg cdg
